service: feedbrainer
image: mterenzi/feedbrainer

servers:
  web:
    - 192.168.0.1 # UPDATE THIS with your server IP
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

proxy:
  ssl: true
  host: open.news
  app_port: 3000
  secure: true

registry:
  # server: ghcr.io
  username: mterenzi
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 192.168.0.1 # UPDATE THIS (usually same as web server for single node)
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - SMTP_ADDRESS
    - SMTP_PORT
    - SMTP_DOMAIN
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - APP_DOMAIN

aliases:
  console: app exec -i --reuse "bin/rails console"
  shell: app exec -i --reuse "bash"
  logs: app logs -f
  dbc: app exec -i --reuse "bin/rails dbconsole"
